spring.application.name=veebipood
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d7fqebd8nd3s73e37reg-a.ohio-postgres.render.com/veebipood_database_ee51
spring.datasource.username=veebipood_user
spring.datasource.password=fhKlB77XFPaZE7xQfLqZLwdc1mmf5164
